### ISSUE TITLE
Polynomials - Exponent Properties 5.1​ Example 12

### ISSUE THREAD

**Issue by virgilpierce** [andrasbalogh/CollegePrepMathematics#1]
the solution is wrong. It should be a^6b^2 / c^16a^10

**Comment by andrasbalogh** [comment]
What is the file name of the problem?

**Comment by virgilpierce** [comment]
CollegePrepMathematics/setWallace-A-5.1_Exponent_properties/16IntAlg_16_Exponents.pg

**Comment by andrasbalogh** [comment]
Please double check.
16IntAlg_16_Exponents.pg (#12) has only one variable.
16IntAlg_12_Exponents.pg  (#11) is the one with three variables and it seems to be working fine.
The powers are higher in the numerator than in the denominator, so the example you write should not even come up. But if it comes up why not simplify the powers of a?
Do you know the seed for the case it does not work or the course and instructor/student?

**Comment by virgilpierce** [comment]
I think we can close this issue.
