### ISSUE TITLE
Fixed Answer Tolerance

### ISSUE THREAD

**Issue by virgilpierce** [andrasbalogh/CollegePrepMathematics#4]
Answer Tolerance on CollegePrepMathematics/setWallace-B_Final_Exam_16/Spring16-B17.pg 
was not set to the specified nearest three decimal places.

Correct PG code is to replace answer checker with:

ANS( Compute("$bigcups")->cmp(tolerance => .001 ) );

**Comment by andrasbalogh** [comment]
fixed on the server
