### ISSUE TITLE
Wallace 7.8 Problem #10

### ISSUE THREAD

**Issue by virgilpierce** [andrasbalogh/CollegePrepMathematics#6]
Path:  CollegePrepMathematics/setWallace-B-7.8_Dimensional_Analysis/wallace_DA6.pg

Problem mixes ft and yards, which is appropriate in this section, however the answer is incorrect.  

It should be:  $answer1 = ($a*$b)/$c/9;

rather than: $answer1 = ($a*$b)/$c;

**Comment by andrasbalogh** [comment]
Changed it on the server to
$answer1 = ($a*$b)*$c/9;
I think that is the correct formula.
