### ISSUE TITLE
Problem Set Wallace-A-4.1

### ISSUE THREAD

**Issue by virgilpierce** [andrasbalogh/CollegePrepMathematics#8]
Problem set is "Graphing Systems of Equations".  There are two issues that will require reworking the problem set:

1.  Problem number 2 is looking for the solution as a parametrized expression for the line (x, m*x+b); the problem text should indicate this - however similar text should be added to other problems in the set.

2.  Teacher (Pioneer HS, Sharyland ISD) has requested more problems in this set.

**Comment by andrasbalogh** [comment]
#1 is similar question, but with unique solution.
Added on the server the text: 
Type your answer as a point: (a,b).
If there are infinitely many solutions type your answer in the form: (x, mx+b).
If there is no solution type: none

Will open a separate issue for #2.
